name: Deploy pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Instalar las dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: Test
        run: npm test
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
          token: ${{secrets.TOKEN_PERSONAL}}
